apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  aws_access_key_id: {{ .Values.aws_access_key_id }}
  aws_secret_access_key: {{ .Values.aws_secret_access_key }}
