{
 "title": "CSYE7125 Metrics Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "webapp",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "webapp_API_call_counter",
     "type": "stat",
     "gridPos": { "h": 13, "w": 6, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "sum(register_user{instance=\"webapp\"})",
       "legendFormat": "register_user"
      },
      {
       "expr": "sum(login_user{instance=\"webapp\"})",
       "legendFormat": "login_user"
      },
      {
       "expr": "sum(update_user{instance=\"webapp\"})",
       "legendFormat": "update_user"
      },
      {
       "expr": "sum(fetch_user_without_authentication{instance=\"webapp\"})",
       "legendFormat": "fetch_user_without_authentication"
      },
      {
       "expr": "sum(fetch_user_with_authentication{instance=\"webapp\"})",
       "legendFormat": "fetch_user_with_authentication"
      },
      {
       "expr": "sum(get_a_watch{instance=\"webapp\"})",
       "legendFormat": "get_a_watch"
      },
      {
       "expr": "sum(get_all_watch{instance=\"webapp\"})",
       "legendFormat": "get_all_watch"
      },
      {
       "expr": "sum(create_watch{instance=\"webapp\"})",
       "legendFormat": "create_watch"
      },
      {
       "expr": "sum(update_watch{instance=\"webapp\"})",
       "legendFormat": "update_watch"
      },
      {
       "expr": "sum(delete_watch{instance=\"webapp\"})",
       "legendFormat": "delete_watch"
      },
      {
       "expr": "counter_kafka_topic_watch_producer",
       "legendFormat": "kafka_topic_watch_producer"
      }
     ]
    },
    {
     "title": "mysql_counter",
     "type": "stat",
     "gridPos": { "h": 13, "w": 6, "x": 6, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "sum(counter_mysql_insert_new_user{instance=\"webapp\"})",
       "legendFormat": "mysql_insert_new_user"
      },
      {
       "expr": "sum(counter_mysql_fetch_user{instance=\"webapp\"})",
       "legendFormat": "mysql_fetch_user"
      },
      {
       "expr": "sum(counter_mysql_update_user{instance=\"webapp\"})",
       "legendFormat": "mysql_update_user"
      },
      {
       "expr": "sum(counter_mysql_insert_new_watch{instance=\"webapp\"})",
       "legendFormat": "mysql_insert_new_watch"
      },
      {
       "expr": "sum(counter_mysql_fetch_watch{instance=\"webapp\"})",
       "legendFormat": "mysql_fetch_watch"
      },
      {
       "expr": "sum(counter_mysql_update_watch{instance=\"webapp\"})",
       "legendFormat": "mysql_update_watch"
      },
      {
       "expr": "sum(counter_mysql_delete_watch{instance=\"webapp\"})",
       "legendFormat": "mysql_delete_watch"
      },
      {
       "expr": "sum(counter_mysql_insert_new_alert{instance=\"webapp\"})",
       "legendFormat": "mysql_insert_new_alert"
      },
      {
       "expr": "sum(counter_mysql_fetch_alert{instance=\"webapp\"})",
       "legendFormat": "mysql_fetch_alert"
      }
     ]
    },
    {
     "title": "database_call_timer",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg(mysql_insert_new_user{instance=\"webapp\"})",
       "legendFormat": "mysql_insert_new_user"
      },
      {
       "expr": "avg(mysql_fetch_user{instance=\"webapp\"})",
       "legendFormat": "mysql_fetch_user"
      },
      {
       "expr": "avg(mysql_update_user{instance=\"webapp\"})",
       "legendFormat": "mysql_update_user"
      },
      {
       "expr": "avg(mysql_insert_new_watch{instance=\"webapp\"})",
       "legendFormat": "mysql_insert_new_watch"
      },
      {
       "expr": "avg(mysql_fetch_watch{instance=\"webapp\"})",
       "legendFormat": "mysql_fetch_watch"
      },
      {
       "expr": "avg(mysql_update_watch{instance=\"webapp\"})",
       "legendFormat": "mysql_update_watch"
      },
      {
       "expr": "avg(mysql_delete_watch{instance=\"webapp\"})",
       "legendFormat": "mysql_delete_watch"
      },
      {
       "expr": "avg(mysql_insert_new_alert{instance=\"webapp\"})",
       "legendFormat": "mysql_insert_new_alert"
      },
      {
       "expr": "avg(mysql_fetch_alert{instance=\"webapp\"})",
       "legendFormat": "mysql_fetch_alert"
      },
      {
       "expr": "avg(kafka_topic_watch_producer{instance=\"webapp\"})",
       "legendFormat": "kafka_topic_watch_producer"
      }
     ]
    }
   ]
  },
  {
   "title": "poller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "poller_counter",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "sum(kafka_topic_watch_consumer{instance=\"poller\"})",
       "legendFormat": "kafka_topic_watch_consumer"
      },
      {
       "expr": "round(sum(counter_kafka_topic_weather_producer{instance=\"poller\"}) / 3)",
       "legendFormat": "counter_kafka_topic_weather_producer"
      },
      {
       "expr": "sum(counter_weather_api{instance=\"poller\"})",
       "legendFormat": "weather_api"
      },
      {
       "expr": "sum(counter_mysql_insert_poller_alert{instance=\"poller\"})",
       "legendFormat": "mysql_insert_poller_alert"
      },
      {
       "expr": "sum(counter_mysql_fetch_poller_alert{instance=\"poller\"})",
       "legendFormat": "mysql_fetch_poller_alert"
      },
      {
       "expr": "sum(counter_mysql_delete_poller_alert{instance=\"poller\"})",
       "legendFormat": "mysql_delete_poller_alert"
      }
     ]
    },
    {
     "title": "poller_timer",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg(gauge_kafka_topic_weather_producer{instance=\"poller\"})",
       "legendFormat": "kafka_topic_weather_producer"
      },
      {
       "expr": "avg(weather_api{instance=\"poller\"})",
       "legendFormat": "weather_api"
      }
     ]
    },
    {
     "title": "poller_mysql_timer",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg(mysql_insert_poller_alert{instance=\"poller\"})",
       "legendFormat": "mysql_insert_poller_alert"
      },
      {
       "expr": "avg(mysql_fetch_poller_alert{instance=\"poller\"})",
       "legendFormat": "mysql_fetch_poller_alert"
      },
      {
       "expr": "avg(mysql_delete_poller_alert{instance=\"poller\"})",
       "legendFormat": "mysql_delete_poller_alert"
      }
     ]
    }
   ]
  },
  { "title": "notifier", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "notifier_counter",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "round(sum(kafka_topic_weather_consumer{instance=\"notifier\"}) / 3)",
     "legendFormat": "kafka_topic_weather_consumer"
    },
    {
     "expr": "sum(counter_mysql_insert_alert_status{instance=\"notifier\"})",
     "legendFormat": "mysql_insert_alert_status"
    },
    {
     "expr": "sum(counter_mysql_fetch_alert_status{instance=\"notifier\"})",
     "legendFormat": "mysql_fetch_alert_status"
    },
    {
     "expr": "sum(counter_mysql_delete_alert_status{instance=\"notifier\"})",
     "legendFormat": "mysql_delete_alert_statu"
    },
    {
     "expr": "sum(counter_mysql_update_alert_status{instance=\"notifier\"})",
     "legendFormat": "mysql_update_alert_status"
    }
   ]
  },
  {
   "title": "notifer_timer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(mysql_insert_alert_status{instance=\"notifier\"})",
     "legendFormat": "mysql_insert_alert_status"
    },
    {
     "expr": "avg(mysql_fetch_alert_status{instance=\"notifier\"})",
     "legendFormat": "mysql_fetch_alert_status"
    },
    {
     "expr": "avg(mysql_delete_alert_status{instance=\"notifier\"})",
     "legendFormat": "mysql_delete_alert_status"
    },
    {
     "expr": "avg(mysql_update_alert_status{instance=\"notifier\"})",
     "legendFormat": "mysql_update_alert_status"
    }
   ]
  }
 ]
}